class PrefectureCode < ActiveHash::Base

  include ActiveHash::Associations
   has_many :items

   self.data = [
    {id: 1, prefecture_code: '---'},
    {id: 2, prefecture_code: '北海道'},
    {id: 3, prefecture_code: '青森県'},
    {id: 4, prefecture_code: '岩手県'},
    {id: 5, prefecture_code: '宮城県'}, 
    {id: 6, prefecture_code: '秋田県'}, 
    {id: 7, prefecture_code: '山形県'},
    {id: 8, prefecture_code: '福島県'},
    {id: 9, prefecture_code: '茨城県'}, 
    {id: 10, prefecture_code: '栃木県'},
    {id: 11, prefecture_code: '群馬県'},
    {id: 12, prefecture_code: '埼玉県'}, 
    {id: 13, prefecture_code: '千葉県'},
    {id: 14, prefecture_code: '東京都'}, 
    {id: 15, prefecture_code: '神奈川県'},
    {id: 16,prefecture_code: '新潟県'},
    {id: 17, prefecture_code: '富山県'},
    {id: 18, prefecture_code: '石川県'},
    {id: 19, prefecture_code: '福井県'},
    {id: 20, prefecture_code: '山梨県'},
    {id: 21, prefecture_code: '長野県'},
    {id: 22, prefecture_code: '岐阜県'},
    {id: 23, prefecture_code: '静岡県'}, 
    {id: 24, prefecture_code: '愛知県'},
    {id: 25, prefecture_code: '三重県'},
    {id: 26, prefecture_code: '滋賀県'}, 
    {id: 27, prefecture_code: '京都府'}, 
    {id: 28, prefecture_code: '大阪府'},
    {id: 29, prefecture_code: '兵庫県'},
    {id: 30, prefecture_code: '奈良県'},
    {id: 31, prefecture_code: '和歌山県'},
    {id: 32, prefecture_code: '鳥取県'},
    {id: 33, prefecture_code: '島根県'},
    {id: 34, prefecture_code: '岡山県'},
    {id: 35, prefecture_code: '広島県'}, 
    {id: 36, prefecture_code: '山口県'},
    {id: 37, prefecture_code: '徳島県'},
    {id: 38, prefecture_code: '香川県'}, 
    {id: 39, prefecture_code: '愛媛県'}, 
    {id: 40, prefecture_code: '高知県'},
    {id: 41, prefecture_code: '福岡県'}, 
    {id: 42, prefecture_code: '佐賀県'},
    {id: 43, prefecture_code: '長崎県'},
    {id: 44, prefecture_code: '熊本県'}, 
    {id: 45, prefecture_code: '大分県'}, 
    {id: 46, prefecture_code: '宮崎県'},
    {id: 47, prefecture_code: '鹿児島県'},
    {id: 48, prefecture_code: '沖縄県'}
  ]
end